#!/bin/bash

# USAGE: provision/prepare-provision

fail() {
  echo "$*" >&2
  exit 1
}

cp -R provision.sh provision/provision.sh
(( "$?" == "0" )) ||
  fail "Could not copy the original provision.sh file to the provision folder."

assure_string_in_file() {
  assurefilename=$1
  assuresearchString=$2
  assurereplaceString=$3

  re="s#^.*$assuresearchString.*#$assurereplaceString#"

  #Detect OSX v other linux for sed ''
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "${re}" "$assurefilename"
    (( "$?" == "0" )) ||
      fail "Could not execute execute sed command replace $assuresearchString with $assurereplaceString in file $assurefilename, terminating install."
  else
    sed -i "${re}" "$assurefilename"
    (( "$?" == "0" )) ||
      fail "Could not execute execute sed command replace $assuresearchString with $assurereplaceString in file $assurefilename, terminating install."
  fi

}

filename_provision="provision/provision.sh"
assure_string_in_file $filename_provision 'OS_USERNAME=${1}' "OS_USERNAME=\"$(terraform output username)\""
assure_string_in_file $filename_provision 'OS_API_KEY=${2}' "OS_API_KEY=\"$(terraform output password)\""
assure_string_in_file $filename_provision 'OS_TENANT=${3}' "OS_TENANT=\"$(terraform output tenant_name)\""
assure_string_in_file $filename_provision 'OS_AUTH_URL=${4}' "OS_AUTH_URL=\"$(terraform output auth_url)\""
assure_string_in_file $filename_provision 'OS_REGION=${5}' "OS_REGION=\"$(terraform output region)\""
assure_string_in_file $filename_provision 'CF_SUBNET1=${6}' "CF_SUBNET1=\"$(terraform output internal_network_id)\""
assure_string_in_file $filename_provision 'IPMASK=${7}' "IPMASK=\"$(terraform output network)\""
assure_string_in_file $filename_provision 'CF_IP=${8}' "CF_IP=\"$(terraform output cf_fp_address)\""
assure_string_in_file $filename_provision 'CF_SIZE=${9}' "CF_SIZE=\"$(terraform output cf_size)\""
assure_string_in_file $filename_provision 'CF_BOSHWORKSPACE_VERSION=${10}' "CF_BOSHWORKSPACE_VERSION=\"$(terraform output cf_boshworkspace_version)\""
assure_string_in_file $filename_provision 'CF_DOMAIN=${11}' "CF_DOMAIN=\"$(terraform output cf_domain)\""
assure_string_in_file $filename_provision 'DOCKER_SUBNET=${12}' "DOCKER_SUBNET=\"$(terraform output docker_subnet)\""
assure_string_in_file $filename_provision 'INSTALL_DOCKER=${13}' "INSTALL_DOCKER=\"$(terraform output install_docker_services)\""
